### PR TITLE
Added iOS framework for Carthage support.

### PR DESCRIPTION
**Pull request by robertjpayne**
Would be great to have dynamic framework support so Carthage can work on DFCache. Tried to keep the setup as close to the way you have files organised for the static libs!

### CODE REVIEW

**Comment by robertjpayne** [comment]
Closing this until I can actually fix the framework working once embedded.

**Comment by kean** [comment]
Thanks! Feel free to reorganise the project and podpsec (it's not optimal) if necessary.

**Comment by robertjpayne** [comment]
@kean think I have this all working now!

**Comment by kean** [comment]
Thank you. I've built it using Carthage and it worked well for both device and simulator.

However, the are two minor issues:

1) I receive warnings about an incomplete umbrella header:

screen shot 2015-08-09 at 17 34 07

Xcode automatically uses DFCache.h file as an umbrella header when building "DFCache iOS Framework" target. Xcode uses a header file with the same name as a target's "Product Name". I would recommend to rename DFCache.h and DFCache.m files to something else (like DFCacheImpl.h and DFCacheImpl.m) and make DFCache.h a proper [umbrella header file](https://gist.github.com/kean/f97b635a29de33ea5b9e). Or alternatively to change the framework product name to something like DFCacheKit or DFCacheFramework and add an umbrella file with a corresponding name.

2) And please delete these two unused folders:

screen shot 2015-08-09 at 17 44 19

**Comment by robertjpayne** [comment]
@kean that's a really tricky one to fix because it'll break the other targets -- let me research up on how we could potentially fix that warning.

**Comment by kean** [comment]
@robertjpayne I've used the second approach in DFImageManager. An umbrella header is only used by a framework and is not included in library source files
screen shot 2015-08-09 at 17 52 33

It doesn't build using Carthage though (because of dependencies declared using CocoaPods), but it does build in Xcode.

**Comment by robertjpayne** [comment]
@kean want to give these two last commits a look?

* I added the imports directly to DFCache so the static modules should still work fine as well.
* I moved the "DFCacheExtended" methods directly into DFCache because we needed to get rid of the circular import.
* Added another necessary UIKit import (wrapped inside a #define)

**Comment by robertjpayne** [comment]
Also just fixed the test suite.

**Comment by kean** [comment]
> I moved the "DFCacheExtended" methods directly into DFCache because we needed to get rid of the circular import.

I'm ok with that :+1:

I can't get rid of this weird error when building it using Carthage:

```
~/Documents/Carthage @ host-192-168-1-36 (kean) 
~> carthage update
*** Fetching DFCache
*** Checking out DFCache at "30144df8bb7e157c625d0e48166eeac0cf93a71d"
*** xcodebuild output can be found in /var/folders/d1/d34_w5tj47lfm9szwgzr4tr00000gn/T/carthage-xcodebuild.JJTq8j.log
*** Building scheme "DFCache iOS Framework" in DFCache.xcodeproj
2015-08-09 18:23:18.600 xcodebuild[7359:368077] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KSHObjcUML.xcplugin' not present in DVTPlugInCompatibilityUUIDs
xcodebuild: error: Failed to build project DFCache with scheme DFCache iOS Framework.
	Reason: The run destination iPad 2 is not valid for Running the scheme 'DFCache iOS Framework'.
A shell task failed with exit code 70:
2015-08-09 18:23:18.600 xcodebuild[7359:368077] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KSHObjcUML.xcplugin' not present in DVTPlugInCompatibilityUUIDs
xcodebuild: error: Failed to build project DFCache with scheme DFCache iOS Framework.
	Reason: The run destination iPad 2 is not valid for Running the scheme 'DFCache iOS Framework'.
```

Carthage file:
```
github "robertjpayne/DFCache" "master"
```

**Comment by robertjpayne** [comment]
@kean have you cleared your derrived data folder? Carthage doesn't do any cleaning so it may be a good idea to.

**Comment by kean** [comment]
It seems like it's trying to build it for iOS 7.1 simulator
screen shot 2015-08-09 at 18 27 50

**Comment by robertjpayne** [comment]
@kean I've had some weird issues with CLI building before like this too, the scheme was set to iPhone 6 when I last had it opened but I don't believe the xcuserdata is committed anyways.

**Comment by kean** [comment]
https://github.com/Carthage/Carthage/issues/417

**Comment by robertjpayne** [comment]
hah dang, I don't have that simulator installed so explains a bit

**Comment by kean** [comment]
Well, there are lots of similar issues:
https://github.com/Carthage/Carthage/issues/259
https://github.com/Carthage/Carthage/pull/653

Deleting iPad 2 7.1 simulator fixed the issue. The funny thing that at first it was building just fine, then I guess something changed in Xcode environment. Too bad Carthage doesn't seem to have a fix for this issue.

Ok, I'm merging your PR, everything seems to work. I will try to workaround an umbrella header issue later. I'm not happy with the way it's handled neither in DFCache nor in DFImageManager.

**Comment by robertjpayne** [comment]
@kean the umbrella header issue should be fixed now since the `DFCache.h` contains all the header files.

I think typically frameworks don't have a class that is the same name as the framework so that's probably the direction to go to attempt to fix it.

**Comment by robertjpayne** [comment]
And again thanks for the awesome caching library!

**Comment by kean** [comment]
Thanks for the PR! :octocat:

**Comment by kean** [comment]
> I think typically frameworks don't have a class that is the same name as the framework so that's probably the direction to go to attempt to fix it.

@robertjpayne just found out that Xcode allows you to provide custom .modulemap file that in turn can specify custom umbrella header file

**Pull request merged**
